imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_mainmenu.module'
      $context: '@oksydan.is_mainmenu.context'
      $dbPrefix: '%database_prefix%'

  Oksydan\IsMainMenu\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Exception,Entity,Controller,Form,Grid,Factory,Handler}'
      - '../../src/index.php'
      - '../../src/*/index.php'
