
services:
  _defaults:
    public: true

  oksydan.is_mainmenu.grid.data.factory.menu_list_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@Oksydan\IsMainMenu\Grid\Query\MenuListQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_mainmenu_list'

  oksydan.is_mainmenu.grid.menu_list_grid_factory:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@Oksydan\IsMainMenu\Grid\Definition\Factory\MenuListGridDefinitionFactory'
      - '@Oksydan\IsMainMenu\Grid\Data\Factory\MenuListGridDataFactory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

