imports:
  - { resource: ../common.yml }
  - { resource: grid.yml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_mainmenu.module'
      $context: '@oksydan.is_mainmenu.context'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'
      $multistoreFeature: '@prestashop.adapter.multistore_feature'
      $contextAdapter: '@prestashop.adapter.shop.context'
      $dbPrefix: '%database_prefix%'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(false)'
      $langRepository: '@prestashop.core.admin.lang.repository'
      $menuListDataFactory: '@oksydan.is_mainmenu.grid.data.factory.menu_list_data_factory'

  oksydan.is_mainmenu.menu_element_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Oksydan\IsMainMenu\Form\Type\MenuElementType'
      - '@Oksydan\IsMainMenu\Form\Provider\MenuElementFormDataProvider'

  Oksydan\IsMainMenu\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Exception,Entity,Controller}'
      - '../../src/Handler/File/*'
      - '../../src/index.php'
      - '../../src/*/index.php'

