services:
  _defaults:
    public: true

  oksydan.is_mainmenu.module:
    class: Is_mainmenu
    public: true
    autowire: false
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'is_mainmenu'

  oksydan.is_mainmenu.context:
    class: Context
    factory: [ '\Context', getContext ]
